[blocked] infra: update dependencies for mdbook preprocessors
Needs https://github.com/rust-lang/mdBook/pull/2401 to land before it
can be landed, because mdbook requires pulldown-cmark 0.10, so there is
a type mismatch on `Event`:

```
error[E0271]: expected `Parser<'_>` to be an iterator that yields `Event<'_>`, but it yields `Event<'_>`
   --> src/lib.rs:372:39
    |
372 |             html::push_html(&mut buf, events);
    |             ---------------           ^^^^^^ expected `Event<'_>`, found `pulldown_cmark::Event<'_>`
    |             |
    |             required by a bound introduced by this call
    |
    = note: `pulldown_cmark::Event<'_>` and `Event<'_>` have similar names, but are actually distinct types
note: `pulldown_cmark::Event<'_>` is defined in crate `pulldown_cmark`
   --> /Users/chris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pulldown-cmark-0.10.3/src/lib.rs:354:1
    |
354 | pub enum Event<'a> {
    | ^^^^^^^^^^^^^^^^^^
note: `Event<'_>` is defined in crate `pulldown_cmark`
   --> /Users/chris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pulldown-cmark-0.11.0/src/lib.rs:366:1
    |
366 | pub enum Event<'a> {
    | ^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `pulldown_cmark` are being used?
```